### ISSUE TITLE
Data ownership and data privacy rules?

### ISSUE THREAD

**Issue by nislah** [HUB4NGI/NGI-map#10]
How the actor’s data is handled after the HUB4NGI project?
=> Who is the data owner?
=> Who is the data processor (HUB4NGI or Open University)?
=> What kind of privacy rules are applied?

**Comment by alexmikro** [comment]
We've tried to define these rules in the Privacy Statement https://map.hub4ngi.eu/map/privacy.php (link available in the map's footer). Feel free to revise this accordingly.

**Comment by Lahnis2** [comment]
Better lawyer to check it.
Btw: created a new profile @Lahnis2 to receive emails to Martel email. Will use it from now on.

**Comment by alexmikro** [comment]
@Lahnis2 I've sent an invite to join this repository to your new id.

Regarding the Policy Statement, this is the standard text (with slight modifications) that we use for websites produced in our lab. Of course you are welcome to involve lawyers for an extra check.

**Comment by Lahnis2** [comment]
Please Change the privacy policy link to https://www.hub4ngi.eu/privacy-policy/
