### ISSUE TITLE
NGI News subscribtion add-on text for the NGI Map registration and confirmation email

### ISSUE THREAD

**Issue by Lahnis2** [HUB4NGI/NGI-map#14]
Please add on the NGI Map (actor) registration page within the “About Your Organisation:” - below “Your Email” a text (check grammar):
“You will be added automatically to the NGI mailing list to get latest updates about the Next Generation Internet (NGI). When receiving NGI news you have an option to unsubscribe.”
 
For the confirmation email to add:
“To stay always updated and to get latest Next Generation Internet (NGI) news you have been added on the NGI mailing list. When receiving NGI news you have an option to unsubscribe.”

**Comment by alexmikro** [comment]
Merging this with #2
