### ISSUE TITLE
Country search, SME benefits

### ISSUE THREAD

**Issue by Lahnis2** [HUB4NGI/NGI-map#16]
FIF meeting 29.1.2018 feedback:
1) Include a country search to find easier local NGI stakeholders - Timeline: by the end of Q3/2018.
2) To make benefits for SMEs better visible either on the NGI.eu web or on the NGI Map - Timeline: by the end of Q2/2018.

The 2) above would mean e.g. a pop-up window where benefits (TBD) are listed, e.g.:
The NGI map brings many advantages to participants:
- A marketing channel to promote work and expertise, leading to increased visibility and reach.
- Standing out as supporting a new initiative for the development of the future Internet.
- Being able to shape and refine the NGI R&D agenda, planned activities and instruments.
- Joining a true pan-European partnership: national – EU – international
- Participating in the NGI activities by fostering collaborations with top-notch players.

**Comment by aba-sah** [comment]
Country search available via free text search field
