### ISSUE TITLE
Hover text over the “3 lines”

### ISSUE THREAD

**Issue by Lahnis2** [HUB4NGI/NGI-map#18]
Please add a hover over the “3 lines” to indicate e.g. “Open menu bar to add, view, filter actor(s)”.

**Comment by aba-sah** [comment]
Done. There is a short delay for popup to display.

Note this works in Chrome. 
Map works in Firefox but does not display icons on load - need to select in filter to show.
Map does not display in Safari on OSX but works in Safari on iOS

**Comment by Lahnis2** [comment]
The icons MUST be visible right a way in the FIREFOX also! Please try to correct it ASAP!
