### ISSUE TITLE
Pop-up window (limited time) to explain benefits of being on the map

### ISSUE THREAD

**Issue by Lahnis2** [HUB4NGI/NGI-map#19]
FIF meeting 29.1.2018 [AI-FIF180129-HUB-04]: Based on [AI-FIF180129-EC-05]: 
To make benefits for SMEs better visible either on the NGI.eu web or on the NGI Map - Timeline: by the end of Q2/2018.

**Comment by Lahnis2** [comment]
This was added again because could not find it anymore

**Comment by aba-sah** [comment]
May be moved to Jul milestone.

**Comment by Lahnis2** [comment]
If delayed, possible to have ASAP in the footer "Add, edit, filter actors by clicking |||" or similar? (3 lines must of course be horisontal)

**Comment by aba-sah** [comment]
Included in delivery for Aug milestone as per roadmap June 2018
