### ISSUE TITLE
Delete an actor

### ISSUE THREAD

**Issue by alexmikro** [HUB4NGI/NGI-map#3]
When users edit an existing actor (via the unique link sent to them) they should also be able to delete this actor (after confirmation with an alert window). 

If they delete the actor, the database entry should be removed and their email address should be removed from the mailing list of #2 .

**Comment by nislah** [comment]
Have all actors (also first registered) received the unique link sent to them by email?

**Comment by alexmikro** [comment]
No, the first few actors have not received the unique link as this feature was added later. I've added this as a new issue: #9
