### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by alexmikro** [HUB4NGI/NGI-map#4]
In order to export more than just email addresses (see #2 ) we will need to create an API. Access to this API will need to be authenticated. We will need to discuss what functions this API should support, e.g. export, import of data, etc.

**Comment by nislah** [comment]
Related to API maybe:
1) A method needed to get a nr. of each type of actors and total nr. of actors.
2) Step-by-step instructions needed how to get the email addresses from the registered actors and nr. of each type of actors and total nr. of actors.

**Comment by alexmikro** [comment]
In light of the latest discussions, this issue is now renamed to "Reports" and will be about extracting data from the map not via an API, but via a reporting interface that will provide (at first) a list of the registered emails and the number of registered actors per organisation type. More types of reports may be added later.

**Comment by Lahnis2** [comment]
Please provide instructions how to get this information!
