### ISSUE TITLE
Register initiatives

### ISSUE THREAD

**Issue by alexmikro** [HUB4NGI/NGI-map#5]
Something discussed at the FIF: would it be possible to register main initiatives for matchmaking purposes? How can these initiatives be added? They do not have a location on the map, so they can't be added as another actor type.

**Comment by aba-sah** [comment]
Current ideas for implementation; feedback to be gathered during NGI Contacts webinar end April
- current suggestions are to allow initiatives to be created with an owner
- other registered organisations may join the initiative

to be displayed on the map initiatives will be attached to the owner and spread by other contributor organisations

**Comment by Lahnis2** [comment]
NOT working:
Creation seems to work but there are bugs:
1. big X is covering the form (at least in chrome) - see screenshot in 19.10. email to MapSupport by Lahnis 
2. after creation you are logged out, and you don't understand if creation worked.
3. If I log back, i can see the initiative in my initiative, but can't edit it.
4. Report visualization is unreadable
5. if i click on show initiatives, I can't see a difference with the normal map. 
Same happens for other registered user (for separate company): Can't see any initiatives on the map!

**Comment by Lahnis2** [comment]
> NOT working:
> Creation seems to work but there are bugs:
> 
> 1. big X is covering the form (at least in chrome) - see screenshot in 19.10. email to MapSupport by Lahnis
> 2. after creation you are logged out, and you don't understand if creation worked.
> 3. If I log back, i can see the initiative in my initiative, but can't edit it.
> 4. Report visualization is unreadable
> 5. if i click on show initiatives, I can't see a difference with the normal map.
>    Same happens for other registered user (for separate company): Can't see any initiatives on the map!

6. Better to have the Initiative pin on top of actor logos to see some functionality with the "Show/Hide Initiative"

**Comment by Lahnis2** [comment]
> > NOT working:
> > Creation seems to work but there are bugs:
> > 
> > 1. big X is covering the form (at least in chrome) - see screenshot in 19.10. email to MapSupport by Lahnis
> > 2. after creation you are logged out, and you don't understand if creation worked.
> > 3. If I log back, i can see the initiative in my initiative, but can't edit it.
> > 4. Report visualization is unreadable
> > 5. if i click on show initiatives, I can't see a difference with the normal map.
> >    Same happens for other registered user (for separate company): Can't see any initiatives on the map!
> 
> 1. Better to have the Initiative pin on top of actor logos to see some functionality with the "Show/Hide Initiative"

Some functionality in other maps: https://landscape.big-data-value.eu/
