### ISSUE TITLE
Update the Help page

### ISSUE THREAD

**Issue by alexmikro** [HUB4NGI/NGI-map#6]
The Help page would include a list of topics on the top, e.g.:
-  How to add an NGI actor
-  How to filter data
-  How to find NGI community actors
-  How to edit data
-  How to delete an actor
-  How to get additional support

**Comment by nislah** [comment]
Also slides about the topics above needed (screenshots).

**Comment by alexmikro** [comment]
Updated the help page with the delete actor feature. We'll keep updating the page when new features are added to the map.
