### ISSUE TITLE
Prepare the NGI interactive map feature roadmap (API, extended search, how to add initiatives, etc.)

### ISSUE THREAD

**Issue by nislah** [HUB4NGI/NGI-map#8]
An action item at the FIF 28 June 2017 meeting [AI-FIF170628-HUB-02]: Prepare the NGI interactive map feature roadmap (API, extended search, how to add initiatives, etc.).

**Comment by alexmikro** [comment]
To be done as soon as the relevant issues are complete: #1 #2 #3 #4 #5 
What form should this roadmap have? Any examples of other such roadmaps would be helpful.

**Comment by Lahnis2** [comment]
Template example: 
![image](https://user-images.githubusercontent.com/31214475/29554657-a4e32e92-8728-11e7-8274-c76c4cf5e971.png)
Title would be: NGI Feature Roadmap
Timing: quarter or half a year (instead of year in the picture).
