### ISSUE TITLE
Generate a unique editing link for the first registered actors

### ISSUE THREAD

**Issue by alexmikro** [HUB4NGI/NGI-map#9]
The first few actors that registered on the map have not received the unique link as this feature was added later. A link should be generated and sent to each of them, so that they can later edit or delete their details.

**Comment by alexmikro** [comment]
I can manually send the links via email.

**Comment by Lahnis2** [comment]
Martel was one of the 1st registered actors on the NGI Map. We received the notification to info email, but the link does not work (code is missing). Fede checked the db and edit links are missing in the Martel row and for many other users. This is clearly a bug – assume for those who registered 1st. This same question popped up last week in the NGI Forum I already mentioned to Aba-Sah. This error may explain why it is impossible to edit existing (1st registered) actors on the Map.
